/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/react-icon.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes } = useGLTF('/react-icon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.reactIcon.geometry} material={nodes.reactIcon.material} rotation={[Math.PI / 2, 0, 0]} scale={84.189} />
    </group>
  )
}

useGLTF.preload('/react-icon.glb')
